name: GitHub-Profile-3D-Contrib

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

  push:
    branches:
    - master
    - test

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: akeanti
      - name: Commit & Push
        run: |
          git config user.name akeanti
          git config user.email king.mi.srv@gmail.com
          git add -A .
          git commit -m "generated"
          git push
